---
- name: Configure BGP IPv4 neighbors
  cisco.ios.ios_config:
    parents:
      - "router bgp {{ bgp.as_number }}"
    lines:
      - "neighbor {{ item.neighbor }} remote-as {{ item.remote_as }}"
  loop: "{{ bgp.neighbors_ipv4 | default([]) }}"

- name: Configure BGP IPv6 neighbors
  cisco.ios.ios_config:
    parents:
      - "router bgp {{ bgp.as_number }}"
    lines:
      - "neighbor {{ item.neighbor }} remote-as {{ item.remote_as }}"
  loop: "{{ bgp.neighbors_ipv6 | default([]) }}"

- name: Configure BGP IPv4 networks
  cisco.ios.ios_config:
    parents:
      - "router bgp {{ bgp.as_number }}"
      - "address-family ipv4"
    lines:
      - "network {{ item }}"
  loop: "{{ bgp.networks_ipv4 | default([]) }}"

- name: Configure BGP IPv6 networks
  cisco.ios.ios_config:
    parents:
      - "router bgp {{ bgp.as_number }}"
      - "address-family ipv6"
    lines:
      - "network {{ item }}"
  loop: "{{ bgp.networks_ipv6 | default([]) }}"